version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /home/gumroadalerts && git pull && tsc"

workflows:
  deeploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master # only deploy on the master branch