name: deploy
on:
    - push

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 15.4
            - run: npm run setup:ci
            - run: npm run format:check
            - run: npm run lint:check
            - run: npm run test
    build-and-deploy:
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        needs:
            - check
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 15.4
            - run: npm run setup:ci
            - run: npm i serverless@2.39.0
            - run: npx serverless deploy
        env:
            AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            APP_CONFIG: ${{ secrets.APP_CONFIG }}
